// User & Role Types
export type Domain = 'corporate' | 'education';
export type CorporateRole = 'manager' | 'team-member';
export type EducationRole = 'teacher' | 'student';
export type UserRole = string;

export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: UserRole;
  domain: Domain;
}

// Team & Organization
export interface TeamMember {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: string;
  status: 'active' | 'away' | 'busy' | 'offline';
  productivityScore: number;
  tasksCompleted: number;
  totalTasks: number;
}

// Meeting Types
export interface Meeting {
  id: string;
  title: string;
  description?: string;
  startTime: Date;
  endTime: Date;
  status: 'scheduled' | 'live' | 'completed';
  participants: TeamMember[];
  summary?: AISummary;
  transcript?: TranscriptEntry[];
  actionItems?: Task[];
  decisions?: Decision[];
  sourceMeeting?: string;
  /** Meeting join link (Jitsi, GMeet, Zoom, etc.) */
  meetingLink?: string;
}

export interface TranscriptEntry {
  id: string;
  speaker: TeamMember;
  text: string;
  timestamp: Date;
}

export interface AISummary {
  overview: string;
  keyPoints: string[];
  decisions: string[];
  actionItems: string[];
  sentiment: 'positive' | 'neutral' | 'mixed';
}

export interface Decision {
  id: string;
  text: string;
  madeBy: TeamMember;
  timestamp: Date;
}

// Task Types — Kairox Kanban: 5 columns (To Do, In Progress, In Review, Done, Blockers)
export type TaskStatus = 'todo' | 'in_progress' | 'in_review' | 'done' | 'blockers';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  assignee?: TeamMember;
  assignee_id?: string | null;
  assignee_name?: string | null;
  assigned_at?: string | null;
  dueDate?: Date;
  due_date?: string | null;
  subtasks?: string[];
  source_meeting_id?: string | null;
  sourceMeeting?: Meeting;
  createdAt: Date;
  updatedAt: Date;
  isAutoGenerated: boolean;
  completedAt?: Date;
}

// Kanban Types
export interface KanbanColumn {
  id: TaskStatus;
  title: string;
  tasks: Task[];
}

// Analytics Types
export interface ProductivityMetrics {
  score: number;
  trend: 'up' | 'down' | 'stable';
  tasksCompleted: number;
  tasksOverdue: number;
  meetingsAttended: number;
  avgTaskCompletionTime: number;
}

export interface TeamAnalytics {
  teamScore: number;
  trend: 'up' | 'down' | 'stable';
  memberMetrics: MemberMetric[];
  weeklyProgress: WeeklyProgress[];
}

export interface MemberMetric {
  member: TeamMember;
  contributionScore: number;
  tasksCompleted: number;
  meetingParticipation: number;
  trend: 'up' | 'down' | 'stable';
}

export interface WeeklyProgress {
  week: string;
  tasksCompleted: number;
  meetingsHeld: number;
  productivityScore: number;
}

// Education-specific Types
export interface Class {
  id: string;
  name: string;
  subject: string;
  schedule: string;
  students: Student[];
  teacher: Teacher;
}

export interface Teacher extends User {
  classes: Class[];
  department: string;
}

export interface Student extends User {
  enrolledClasses: Class[];
  grade: string;
}

export type MeetingPlatform = 'jitsi' | 'gmeet' | 'zoom' | 'teams';

export interface Lecture {
  id: string;
  title: string;
  class: Class;
  date: Date;
  duration: number;
  summary?: AISummary;
  transcript?: TranscriptEntry[];
  assignments?: Assignment[];
  status: 'scheduled' | 'live' | 'completed';
  /** Meeting link for joining (Jitsi, GMeet, Zoom, Teams) */
  meetingLink?: string;
  /** Platform used for the meeting */
  platform?: MeetingPlatform;
  /** Description of the meeting/lecture */
  description?: string;
}

export interface Assignment {
  id: string;
  title: string;
  description: string;
  dueDate: Date;
  sourceLecture?: Lecture;
  status: 'pending' | 'submitted' | 'graded';
  isAutoGenerated: boolean;
  priority: 'low' | 'medium' | 'high';
}

// Premium Features
export interface PremiumFeature {
  id: string;
  name: string;
  description: string;
  isLocked: boolean;
}

// Notification Types
export interface Notification {
  id: string;
  type: 'task-assigned' | 'deadline-approaching' | 'meeting-summary' | 'overdue' | 'ai-insight';
  title: string;
  message: string;
  timestamp: Date;
  isRead: boolean;
  actionUrl?: string;
}

// Navigation Types
export interface NavItem {
  title: string;
  href: string;
  icon: string;
  badge?: number;
  isPremium?: boolean;
}
