import {
  LayoutDashboard,
  Calendar,
  ListTodo,
  LayoutGrid,
  FileText,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  ArrowUpRight,
  GripVertical,
  Loader2,
} from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { SidebarItem } from "@/components/layout/Sidebar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { format, formatDistanceToNow } from "date-fns";
import { cn } from "@/lib/utils";
import { useParams } from "react-router-dom";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Task, TaskPriority, TaskStatus } from "@/lib/types";
import { useAuth } from "@/context/AuthContext";
import { getProject, updateProjectTask, type ApiTask } from "@/lib/api";
import { DndContext, DragEndEvent, useDraggable, useDroppable } from "@dnd-kit/core";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const columnColors: Record<string, string> = {
  todo: "border-t-muted-foreground",
  in_progress: "border-t-primary",
  in_review: "border-t-amber-500",
  done: "border-t-success",
  blockers: "border-t-destructive",
};

function apiTaskToTask(a: ApiTask): Task {
  return {
    id: a.id,
    title: a.title,
    description: a.description ?? undefined,
    status: a.status,
    priority: a.priority,
    assignee_id: a.assignee_id,
    assignee_name: a.assignee_name ?? undefined,
    assigned_at: a.assigned_at ?? undefined,
    dueDate: a.due_date ? new Date(a.due_date) : undefined,
    due_date: a.due_date,
    subtasks: a.subtasks ?? undefined,
    source_meeting_id: a.source_meeting_id ?? undefined,
    createdAt: new Date(a.created_at),
    updatedAt: new Date(a.updated_at),
    isAutoGenerated: a.is_auto_generated,
    completedAt: a.completed_at ? new Date(a.completed_at) : undefined,
  };
}

const TeamMemberKanban = () => {
  const { token } = useAuth();
  const { workspaceId } = useParams();
  const basePath = `/business/member/workspaces/${workspaceId}`;
  const [tasks, setTasks] = useState<Task[]>([]);
  const [memberDetails, setMemberDetails] = useState<{ id: string; name: string; email: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [taskDialogOpen, setTaskDialogOpen] = useState(false);
  const [dialogTask, setDialogTask] = useState<Task | null>(null);
  const [dTitle, setDTitle] = useState("");
  const [dDescription, setDDescription] = useState("");
  const [dStatus, setDStatus] = useState<TaskStatus>("todo");
  const [dPriority, setDPriority] = useState<TaskPriority>("medium");
  const [dAssigneeId, setDAssigneeId] = useState("");
  const [dAssigneeName, setDAssigneeName] = useState("");
  const [dDue, setDDue] = useState("");
  const [dSubtasks, setDSubtasks] = useState("");
  const [detailSaving, setDetailSaving] = useState(false);

  const fetchProject = useCallback(async () => {
    if (!token || !workspaceId) return;
    setLoading(true);
    try {
      const project = await getProject(token, workspaceId);
      setTasks((project.tasks ?? []).map(apiTaskToTask));
      setMemberDetails(project.member_details ?? []);
    } catch {
      setTasks([]);
      setMemberDetails([]);
    } finally {
      setLoading(false);
    }
  }, [token, workspaceId]);

  useEffect(() => {
    if (token && workspaceId) fetchProject();
  }, [fetchProject, token, workspaceId]);

  const teamMemberSidebarItems: SidebarItem[] = [
    { title: "Dashboard", href: `${basePath}/dashboard`, icon: LayoutDashboard },
    { title: "Meetings", href: `${basePath}/meetings`, icon: Calendar },
    { title: "My Tasks", href: `${basePath}/tasks`, icon: ListTodo, badge: tasks.filter((t) => t.status !== "done").length },
    { title: "Kanban", href: `${basePath}/kanban`, icon: LayoutGrid },
    { title: "Documents", href: `${basePath}/documents`, icon: FileText },
  ];

  const columns = useMemo(
    () =>
      ({
        todo: { id: "todo", title: "To Do" },
        in_progress: { id: "in_progress", title: "In Progress" },
        in_review: { id: "in_review", title: "In Review" },
        done: { id: "done", title: "Done" },
        blockers: { id: "blockers", title: "Blockers" },
      }) satisfies Record<TaskStatus, { id: TaskStatus; title: string }>,
    []
  );

  const tasksByStatus = useMemo(
    () =>
      (Object.keys(columns) as TaskStatus[]).map((status) => ({
        ...columns[status],
        tasks: tasks.filter((task) => task.status === status),
      })),
    [tasks, columns]
  );

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || !token || !workspaceId) return;
    const activeId = String(active.id);
    const overId = String(over.id);
    const validStatuses = new Set(Object.keys(columns) as TaskStatus[]);

    // DnD-kit may report "over" as another card id (task.id) instead of a column id.
    // In that case, drop into the status (column) of that card.
    const overStatus: TaskStatus | null = validStatuses.has(overId as TaskStatus)
      ? (overId as TaskStatus)
      : (tasks.find((t) => t.id === overId)?.status ?? null);

    if (!overStatus) return;
    try {
      await updateProjectTask(token, workspaceId, activeId, { status: overStatus });
      setTasks((prev) =>
        prev.map((task) =>
          task.id === activeId ? { ...task, status: overStatus, updatedAt: new Date() } : task
        )
      );
    } catch {
      fetchProject();
    }
  };

  const openTaskDialog = (task: Task) => {
    setDialogTask(task);
    setDTitle(task.title);
    setDDescription(task.description ?? "");
    setDStatus(task.status);
    setDPriority(task.priority);
    setDAssigneeId(task.assignee_id ?? "");
    setDAssigneeName((task.assignee_name ?? "").trim());
    const rawDue = task.due_date ?? (task.dueDate ? task.dueDate.toISOString() : "");
    setDDue(rawDue ? rawDue.slice(0, 10) : "");
    setDSubtasks(task.subtasks?.join(", ") ?? "");
    setTaskDialogOpen(true);
  };

  const saveTaskDetail = async () => {
    if (!token || !workspaceId || !dialogTask || !dTitle.trim()) return;
    setDetailSaving(true);
    try {
      const member = dAssigneeId ? memberDetails.find((m) => m.id === dAssigneeId) : undefined;
      const subtasks = dSubtasks.trim()
        ? dSubtasks.split(",").map((s) => s.trim()).filter(Boolean)
        : null;
      await updateProjectTask(token, workspaceId, dialogTask.id, {
        title: dTitle.trim(),
        description: dDescription.trim() ? dDescription.trim() : null,
        status: dStatus,
        priority: dPriority,
        assignee_id: dAssigneeId || null,
        assignee_name: member ? member.name : dAssigneeName.trim() || null,
        due_date: dDue.trim() ? `${dDue.trim()}T12:00:00.000Z` : null,
        subtasks,
      });
      await fetchProject();
      setTaskDialogOpen(false);
      setDialogTask(null);
    } finally {
      setDetailSaving(false);
    }
  };

  const DraggableCard = ({ task, onOpen }: { task: Task; onOpen: (t: Task) => void }) => {
    const due = task.dueDate ?? task.due_date;
    const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
      id: task.id,
    });
    const style = transform
      ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` }
      : undefined;
    const assignee = task.assignee_id ? memberDetails.find((m) => m.id === task.assignee_id) : undefined;
    const assigneeLabel = assignee?.name ?? (task.assignee_name?.trim() ? task.assignee_name : null);
    return (
      <Card
        ref={setNodeRef}
        style={style}
        className={cn("shadow-sm hover:shadow-md transition-shadow", isDragging && "opacity-60")}
      >
        <CardContent className="p-2 flex gap-2">
          <button
            type="button"
            className="flex-shrink-0 px-1 rounded-md text-muted-foreground hover:bg-muted cursor-grab active:cursor-grabbing touch-none self-start mt-0.5"
            aria-label="Drag to move"
            {...listeners}
            {...attributes}
          >
            <GripVertical className="h-4 w-4" />
          </button>
          <div
            role="button"
            tabIndex={0}
            className="flex-1 min-w-0 cursor-pointer py-1 text-left"
            onClick={() => onOpen(task)}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                onOpen(task);
              }
            }}
          >
            <div className="pr-1">
              <div className="flex items-start justify-between gap-2 mb-2">
                <p className="font-medium text-sm leading-snug">{task.title}</p>
                {task.isAutoGenerated && (
                  <Badge
                    variant="outline"
                    className="text-[10px] bg-secondary/10 border-secondary/30 text-secondary flex-shrink-0"
                  >
                    <Sparkles className="h-2 w-2 mr-0.5" />
                    AI
                  </Badge>
                )}
              </div>
              <div className="flex items-center gap-2 mb-3 flex-wrap">
                <Badge
                  variant="outline"
                  className={cn(
                    "text-[10px]",
                    task.priority === "urgent" &&
                      "border-destructive text-destructive bg-destructive/10",
                    task.priority === "high" &&
                      "border-warning text-warning bg-warning/10",
                    task.priority === "medium" &&
                      "border-primary text-primary bg-primary/10",
                    task.priority === "low" && "border-muted-foreground"
                  )}
                >
                  {task.priority}
                </Badge>
                {due ? (
                  <span
                    className={cn(
                      "text-[10px] flex items-center gap-1",
                      new Date(due) < new Date() && task.status !== "done"
                        ? "text-destructive"
                        : "text-muted-foreground"
                    )}
                  >
                    {new Date(due) < new Date() && task.status !== "done" ? (
                      <AlertTriangle className="h-2.5 w-2.5" />
                    ) : (
                      <Clock className="h-2.5 w-2.5" />
                    )}
                    {formatDistanceToNow(new Date(due), { addSuffix: true })}
                  </span>
                ) : (
                  <span className="text-[10px] text-muted-foreground">No due date</span>
                )}
              </div>
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  {assigneeLabel ? (
                    <>
                      <Avatar className="h-5 w-5 shrink-0">
                        <AvatarFallback className="text-[8px]">
                          {(assigneeLabel || "?")
                            .split(" ")
                            .map((n) => n[0])
                            .join("")
                            .slice(0, 2)}
                        </AvatarFallback>
                      </Avatar>
                      <span className="text-[10px] text-muted-foreground truncate">{assigneeLabel.split(" ")[0]}</span>
                    </>
                  ) : (
                    <span className="text-[10px] text-muted-foreground">—</span>
                  )}
                </div>
                {task.isAutoGenerated && (
                  <span className="text-[10px] text-muted-foreground flex items-center gap-1 shrink-0">
                    <ArrowUpRight className="h-2.5 w-2.5" />
                    From meeting
                  </span>
                )}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  };

  const DroppableColumn = ({
    status,
    title,
    columnTasks,
  }: {
    status: TaskStatus;
    title: string;
    columnTasks: Task[];
  }) => {
    const { setNodeRef } = useDroppable({ id: status });
    return (
      <div ref={setNodeRef} className="flex-shrink-0 w-72">
        <Card className={cn("shadow-card border-t-4", columnColors[status])}>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                {title}
                <Badge
                  variant="secondary"
                  className="h-5 w-5 rounded-full p-0 flex items-center justify-center text-xs"
                >
                  {columnTasks.length}
                </Badge>
              </CardTitle>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 min-h-[400px]">
            {columnTasks.map((task) => (
              <DraggableCard key={task.id} task={task} onOpen={openTaskDialog} />
            ))}
            {columnTasks.length === 0 && (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center mb-2">
                  <CheckCircle2 className="h-5 w-5 text-muted-foreground" />
                </div>
                <p className="text-sm text-muted-foreground">No tasks here</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    );
  };

  return (
    <DashboardLayout
      sidebarItems={teamMemberSidebarItems}
      sidebarTitle="Team Member"
      sidebarSubtitle="Personal Workspace"
    >
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Kanban Board</h1>
            <p className="text-muted-foreground">
              Only tasks explicitly assigned to someone in meetings appear here. Drag the handle to move; click a card for details and edits.
            </p>
          </div>
          <Badge
            variant="outline"
            className="bg-secondary/10 border-secondary/30 text-secondary"
          >
            <Sparkles className="h-3 w-3 mr-1" />
            AI-Synced
          </Badge>
        </div>

        <DndContext onDragEnd={handleDragEnd}>
          <div className="flex gap-4 overflow-x-auto pb-4">
            {tasksByStatus.map((column) => (
              <DroppableColumn
                key={column.id}
                status={column.id}
                title={column.title}
                columnTasks={column.tasks}
              />
            ))}
          </div>
        </DndContext>

        <Card className="shadow-card">
          <CardContent className="py-4">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4 text-sm">
                <span className="text-muted-foreground">Drag by the grip to update status</span>
                <Badge
                  variant="outline"
                  className="bg-secondary/10 border-secondary/30 text-secondary text-xs"
                >
                  <Sparkles className="h-2.5 w-2.5 mr-1" />
                  AI Generated
                </Badge>
              </div>
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-success" />
                  Done
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-primary" />
                  In Progress
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-warning" />
                  Review
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-destructive" />
                  Blocked
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Dialog
        open={taskDialogOpen}
        onOpenChange={(open) => {
          setTaskDialogOpen(open);
          if (!open) setDialogTask(null);
        }}
      >
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Task details</DialogTitle>
            <DialogDescription>
              View and edit this task. Changes apply for the whole team.
            </DialogDescription>
          </DialogHeader>
          {dialogTask && (
            <div className="space-y-3 text-sm">
              <div className="rounded-md border bg-muted/40 px-3 py-2 space-y-1 text-muted-foreground">
                <p>
                  <span className="font-medium text-foreground">Assigned (recorded): </span>
                  {dialogTask.assigned_at
                    ? format(new Date(dialogTask.assigned_at), "PPp")
                    : "—"}
                </p>
                <p>
                  <span className="font-medium text-foreground">Source meeting ID: </span>
                  {dialogTask.source_meeting_id ?? "—"}
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="tmkd-title">Title</Label>
                <Input id="tmkd-title" value={dTitle} onChange={(e) => setDTitle(e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tmkd-desc">Description</Label>
                <Textarea
                  id="tmkd-desc"
                  value={dDescription}
                  onChange={(e) => setDDescription(e.target.value)}
                  rows={3}
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-2">
                  <Label>Status</Label>
                  <Select value={dStatus} onValueChange={(v) => setDStatus(v as TaskStatus)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="todo">To Do</SelectItem>
                      <SelectItem value="in_progress">In Progress</SelectItem>
                      <SelectItem value="in_review">In Review</SelectItem>
                      <SelectItem value="done">Done</SelectItem>
                      <SelectItem value="blockers">Blockers</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Priority</Label>
                  <Select value={dPriority} onValueChange={(v) => setDPriority(v as TaskPriority)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="low">Low</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="high">High</SelectItem>
                      <SelectItem value="urgent">Urgent</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label>Team member (links account)</Label>
                <Select value={dAssigneeId || "none"} onValueChange={(v) => setDAssigneeId(v === "none" ? "" : v)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Not linked" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">Not linked</SelectItem>
                    {memberDetails.map((mem) => (
                      <SelectItem key={mem.id} value={mem.id}>
                        {mem.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="tmkd-aname">Assignee name (if not linked)</Label>
                <Input
                  id="tmkd-aname"
                  value={dAssigneeName}
                  onChange={(e) => setDAssigneeName(e.target.value)}
                  placeholder="Name from the meeting"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tmkd-due">Due date</Label>
                <Input id="tmkd-due" type="date" value={dDue} onChange={(e) => setDDue(e.target.value)} />
                <p className="text-xs text-muted-foreground">Leave empty if no due date.</p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="tmkd-sub">Subtasks (comma-separated)</Label>
                <Input id="tmkd-sub" value={dSubtasks} onChange={(e) => setDSubtasks(e.target.value)} />
              </div>
            </div>
          )}
          <DialogFooter className="gap-2 sm:gap-0">
            <Button
              variant="outline"
              type="button"
              onClick={() => {
                setTaskDialogOpen(false);
                setDialogTask(null);
              }}
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={saveTaskDetail}
              disabled={!dialogTask || !dTitle.trim() || detailSaving}
            >
              {detailSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save changes"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
};

export default TeamMemberKanban;
